name: 'Restore Build Cache'

description: 'Restore cached dependencies and build artifacts'

inputs:
  cache-key:
    description: 'Cache key to restore'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Restore cached dependencies and build
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.cache/ms-playwright
        key: ${{ inputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-build-
